#pragma once
void chap13TestThrowException();
void chap13TestMultipleExceptions();
void chap13TestMultipleExceptionsTwoTypes();
void chap13TestUncaughtExceptions();
void chap13TestThrowList();
void chap13TestUnspecifiedExceptions();
void chap13TestExtendExceptionClass();
void chap13TestStackUnwindSmartPointers();
void chap13TestStackUnwindCatchThrow();
void chap13TestErrorHandleMemoryAlloc();
void chap13TestErrorHandleNoThrow();
void chap13TestErrorHandleNewHandler();
void chap13TestErrorHandleConstructorTryBlocks();
